### PR TITLE
S222309556

### PR DESCRIPTION
**Pull request by s222309556**

### CODE REVIEW

**Review by XinyaoCheng — CHANGES_REQUESTED** [review]
Hi, do you have any test video, if yes, can you add them in description of your commit. Also it seems there're some conflicts in AndroidManifest.xml, please check it before you created a PR.

**Comment by s222309556** [comment]
> Hi, do you have any test video, if yes, can you add them in description of your commit. Also it seems there're some conflicts in AndroidManifest.xml, please check it before you created a PR.

Hi, I have already resolved the conflicts and uploaded the video. The link is below.
Video Link: https://video.deakin.edu.au/media/t/1_sbtwpsot

**Comment by XinyaoCheng** [comment]
I've already seen your test video, good work! But can you adjust these two locations of words in homepage icon?
image
image
Make they alike 'patient list' one, and then create a new pull request, after that, @ me and I'll merge your changes:)

**Comment by s222309556** [comment]
@XinyaoCheng ,
 I have adjusted the icons on the home page.

**Comment by XinyaoCheng** [comment]
Hi, can you please give me a video or image to show your lastest changes? @s222309556

**Comment by s222309556** [comment]
> Hi, can you please give me a video or image to show your lastest changes? @s222309556


icons-caretk

**Review by XinyaoCheng — APPROVED** [review]
good to go!

**Pull request merged**
