### PR TITLE
view/caretaker conversions

### PR DESCRIPTION
**Pull request by mirahazall**
## Description

Conversion of files in views/caretaker folder from java to kotlin 
The list of files that were converted to Kotlin:
views/caretaker/CaretakerDashboardActivity
views/caretaker/notifications/FallAlertActivity
views/caretaker/notifications/confirmincident/ConfirmIncidentActivity
views/caretaker/notifications/falsealarm/FalseAlertConfirmedActivity

### Todos

- [x] Tested and working locally
- [x] Code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] Code changes documented
- [x] Requested review from >= 2 devs on the team (one frontend and one backend recommended)

### Associated MS Planner Tasks

- [ In views/caretaker, convert all other Java files to Kotlin ](https://tasks.office.com/deakin365.onmicrosoft.com/Home/Task/4p65Xv8FfE-Y_Puier4kx8gAFRIq?Type=TaskLink&Channel=Link&CreatedTime=638604906298560000)

### Known Issues

No issues detected during Android Studio build process

### CODE REVIEW

**Comment by mirahazall** [comment]
@Onwa1kenobi Hi, I ran the command "./gradlew :app:spotlessApply" again and got these errors: 
Screenshot 2024-08-29 at 11 36 49 AM
Could you please tell me how you were able to successfully run this command last time? Did you also get the same errors?

**Comment by Onwa1kenobi** [comment]
@mirahazall can you share what version of JDK version grade is using on your machine? You can find this in the `Settings` menu of Android Studio.

Screenshot 2024-08-30 at 8 20 12 AM

**Comment by mirahazall** [comment]
@Onwa1kenobi 
Screenshot 2024-08-30 at 12 17 44 PM
It seems like I'm using the same version as you. Could the error be due to M1 processor in Mac?

**Comment by Onwa1kenobi** [comment]
I doubt that. I also have the same ARM chip. From the error message, it looks like there is Java versioning conflicts. Can you share the following screenshots? Under `File` -> `Project Structure`.



Screenshot 2024-08-30 at 8 20 12 AM

Screenshot 2024-08-30 at 1 49 08 PM

**Comment by mirahazall** [comment]
@Onwa1kenobi 
Screenshot 2024-08-31 at 8 49 09 AM
Screenshot 2024-08-31 at 8 51 31 AM

**Review by AsherAli22 — APPROVED** [review]

**Pull request merged**
