### PR TITLE
PIN Code for Log in page layout

### PR DESCRIPTION
**Pull request by mitzigarcia6**
## Description

Created a PIN Code layout for the Log in page instead of the regular method using username and password.

### Todos

- [ ] Tested and working locally
- [ ] Code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] Code changes documented
- [ ] Requested review from >= 2 devs on the team (one frontend and one backend recommended)

### How to test

[Add detailed steps to test the changes that have been made]

### Screenshots and/or Gifs

Screenshot 2024-08-21 at 2 04 47 am

### Associated MS Planner Tasks

- [6 Character - Passcode for the caretakers/Admin] (https://tasks.office.com/deakin365.onmicrosoft.com/Home/Task/gab2vCTEu02vG8y3J3ZyoMgAH8eK?Type=TaskLink&Channel=Link&CreatedTime=638597667795970000)

### Known Issues

No issues with the change.

### CODE REVIEW

**Review by AsherAli22 — CHANGES_REQUESTED** [review]
This is only the frontend screen. The Kotlin code is missing here and should be done to cover the scope of the ticket.

**Comment by mitzigarcia6** [comment]
hi @AsherAli22 I created 3 xml pages. 
1. Account Creation
2. Account Authentication - where after signing up, a code will be sent to the email for verifcation
3. Log in page already with PIN code
Screenshot 2024-09-04 at 9 15 31 PM
Screenshot 2024-09-04 at 9 15 39 PM
Screenshot 2024-09-04 at 9 15 47 PM

**Comment by mitzigarcia6** [comment]
Hi @AsherAli22 

Attaching here the MS planner links 
1. Account creation - https://tasks.office.com/deakin365.onmicrosoft.com/en-GB/Home/Planner/#/plantaskboard?groupId=b9325320-8dcf-4204-81c7-46ccdd3b0798&planId=obnY9eRGNEGXqjBUOhDWKcgAFWt1
2. Account Authentication - https://tasks.office.com/deakin365.onmicrosoft.com/en-GB/Home/Planner/#/plantaskboard?groupId=b9325320-8dcf-4204-81c7-46ccdd3b0798&planId=obnY9eRGNEGXqjBUOhDWKcgAFWt1
3. Log in Page - https://tasks.office.com/deakin365.onmicrosoft.com/en-GB/Home/Planner/#/plantaskboard?groupId=b9325320-8dcf-4204-81c7-46ccdd3b0798&planId=obnY9eRGNEGXqjBUOhDWKcgAFWt1

**Review by mitzigarcia6 — COMMENTED** [review]
Reflected the changes as per Figma design.

**Comment by mitzigarcia6** [comment]
hi @AsherAli22 - new xml pages are added: 
1. forgot_the_password: https://tasks.office.com/deakin365.onmicrosoft.com/en-GB/Home/Planner/#/plantaskboard?groupId=b9325320-8dcf-4204-81c7-46ccdd3b0798&planId=obnY9eRGNEGXqjBUOhDWKcgAFWt1

2. create_new_password: https://tasks.office.com/deakin365.onmicrosoft.com/en-GB/Home/Planner/#/plantaskboard?groupId=b9325320-8dcf-4204-81c7-46ccdd3b0798&planId=obnY9eRGNEGXqjBUOhDWKcgAFWt1

3. loading_splash: https://tasks.office.com/deakin365.onmicrosoft.com/en-GB/Home/Planner/#/plantaskboard?groupId=b9325320-8dcf-4204-81c7-46ccdd3b0798&planId=obnY9eRGNEGXqjBUOhDWKcgAFWt1
Screenshot 2024-09-04 at 11 02 36 PM
Screenshot 2024-09-04 at 11 02 48 PM
.com/user-attachments/assets/c0187234-a61e-48fc-810b-8a57c0fcc5a1)
Screenshot 2024-09-04 at 11 02 55 PM

4. loading_log_in: https://tasks.office.com/deakin365.onmicrosoft.com/en-GB/Home/Planner/#/plantaskboard?groupId=b9325320-8dcf-4204-81c7-46ccdd3b0798&planId=obnY9eRGNEGXqjBUOhDWKcgAFWt1

**Comment by mitzigarcia6** [comment]
> This is only the frontend screen. The Kotlin code is missing here and should be done to cover the scope of the ticket.

Hi @AsherAli22 this is only the xml page as discussed. The changes are now reflected as per your approved Figma design.

**Review by AsherAli22 — APPROVED** [review]
LGTM.

**Pull request merged**
