### PR TITLE
Thakurgaurpal patch 1

### PR DESCRIPTION
**Pull request by thakurgaurpal**
## Description

[Describe the change that was made in this PR]

### Todos

- [ ] Tested and working locally
- [ ] Code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] Code changes documented
- [ ] Requested review from >= 2 devs on the team (one frontend and one backend recommended)

### How to test

[Add detailed steps to test the changes that have been made]

### Screenshots and/or Gifs

[Insert screenshots and/or gifs showing the graphic representation of the change]

### Associated MS Planner Tasks

- [Task Title](http://ms_planner_task_link.com)
- [Task Title](http://ms_planner_task_link.com)

### Known Issues

[Describe any known issue with this change]

### CODE REVIEW

**Comment by Onwa1kenobi** [comment]
Hi @thakurgaurpal, I had a look at the changes that were made in this PR, and it looks like you are working on a Flutter project. This is the reason why you have a lot of files changed as the project is different from the team's project which is a native standalone Android application. My suggestion is that you create a fork of the main repository again, and make your contributions there. Please let me know if you need any assistance on this.

**Comment by AsherAli22** [comment]
@thakurgaurpal flutter app is not the goal. everyone needs to stay on same page here.

**Comment by AsherAli22** [comment]
@thakurgaurpal how many times do we have to tell you that the app needs to be in kotlin and not dart(flutter)? Is it going to take decades for you to complete your tasks in kotlin?

**Review by AsherAli22 — CHANGES_REQUESTED** [review]
@thakurgaurpal how many times do we have to tell you that the app needs to be in kotlin and not dart(flutter)? Is it going to take decades for you to complete your tasks in kotlin?

**Comment by thakurgaurpal** [comment]
Hi Asher, currently I’m working on some other task and I’ll make sure they are in kotlin. I’ll make changes to the current work once I’m done with task I’m working on.On 21 Aug 2024, at 11:39 PM, AsherAli22 ***@***.***> wrote:﻿
@AsherAli22 requested changes on this pull request.

@thakurgaurpal how many times do we have to tell you that the app needs to be in kotlin and not dart(flutter)? Is it going to take decades for you to complete your tasks in kotlin?

**Pull request closed without merging**
